# Auto-review all new PRs
auto_review: true

reviewers:
  default:
    prompt: |
      Review this PR for code quality and best practices.
      Focus on:
      - Code readability and maintainability
      - Potential bugs or edge cases
      - Security concerns
      - Performance implications
    language: en
# Trigger auto-review
